### ISSUE TITLE
Errors - on first start (Nugget scenarios)

### ISSUE THREAD

**Issue by NickRimmer** [Platformus/Platformus#186]
I just create empty .NET Core web app. Add nugets, as it described [here](http://docs.platformus.net/en/latest/getting_started/use_as_nuget_packages.html).

1. I got first error _System.InvalidOperationException: 'Cannot resolve scoped service 'ExtCore.Data.Abstractions.IStorage' from root provider.'_

Solution:
```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .UseDefaultServiceProvider(opt => opt.ValidateScopes = false);
}
```

2. Second error _System.ArgumentException: 'Keyword not supported: 'initial catalog'.'_ 
I can't resolve it )= And I think problem is in connection string (I have SQL Server) or in data provider.

My _appsettings.json_

```
{
  "ConnectionStrings": {
    "local": "Data Source=localhost;Initial Catalog=PlatformusTest1;User Id=sa;Password=password"
  },
  "Extensions": {
    "Path": "/Extensions"
  }
}
```

Is SQLite neccesary for start? Or I can set somewhere type of data provider?

**Comment by NickRimmer** [comment]
Exception **Keyword not supported: 'initial catalog'**:
```
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._FastQuery[TEntity](RelationalQueryContext relationalQueryContext, ShaperCommandContext shaperCommandContext, Func`3 materializer, Type contextType, IDiagnosticsLogger`1 logger)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Platformus.Globalization.DefaultCultureManager.<GetCachedCultures>b__12_0()
   at Platformus.DefaultCache.GetWithDefaultValue[T](String key, Func`1 defaultValueFunc, CacheEntryOptions options)
   at Platformus.Globalization.DefaultCultureManager.GetCachedCultures()
   at Platformus.Globalization.DefaultCultureManager.GetFrontendDefaultCulture()
   at Platformus.Globalization.Frontend.Actions.UseLocalizationAction.Execute(IApplicationBuilder applicationBuilder, IServiceProvider serviceProvider)
   at ExtCore.WebApplication.Extensions.ApplicationBuilderExtensions.UseExtCore(IApplicationBuilder applicationBuilder)
   at Platformus.WebApplication.Extensions.ApplicationBuilderExtensions.UsePlatformus(IApplicationBuilder applicationBuilder)
   at PlatformusTest.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in c:\users\me\Documents\Projects\c_charp\PlatformusTest\PlatformusTest\Startup.cs:line 61
```

**Comment by DmitrySikorsky** [comment]
Hi! That means that you specify wrong connection string. Initial catalog usually is used for SQL Server. You are trying to use SQLite as I can see from the exception. So your connection string should look like

`"Default": "Data Source=db.sqlite"`

**Comment by NickRimmer** [comment]
Is it required to use sqlite? Can I use SQL Server?
If I can, how to set to use SQL Server?

My connection string is correct, but for SQL Server, not for SQLIte.

**Comment by DmitrySikorsky** [comment]
Sure! Platformus supports PostgreSQL, SQLite, and SqlServer with EF as ORM.

Just change your SQLite NuGet references to the corresponding SqlServer ones.

**Comment by NickRimmer** [comment]
![image](https://user-images.githubusercontent.com/1754265/44203250-8f78b480-a178-11e8-8145-5875e47e29f9.png)

All of this sqlite nugets must be changed to sqlserver analogs?

**Comment by DmitrySikorsky** [comment]
Yes, sure.

**Comment by NickRimmer** [comment]
After replace all of this libraries to Sql server analogs, I got next error:

> System.TypeLoadException: 'Could not load type 'ExtCore.Data.EntityFramework.SqlServer.IModelRegistrar' from assembly 'ExtCore.Data.EntityFramework.SqlServer, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null'.'

```
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at ExtCore.Infrastructure.ExtensionManager.GetImplementations[T](Func`2 predicate, Boolean useCaching)
   at ExtCore.Infrastructure.ExtensionManager.GetInstances[T](Func`2 predicate, Boolean useCaching, Object[] args)
   at ExtCore.WebApplication.Extensions.ServiceCollectionExtensions.AddExtCore(IServiceCollection services, String extensionsPath, Boolean includingSubpaths, IAssemblyProvider assemblyProvider)
   at Platformus.WebApplication.Extensions.ServiceCollectionExtensions.AddPlatformus(IServiceCollection services, String extensionsPath)
   at PlatformusTest.Startup.ConfigureServices(IServiceCollection services) in c:\users\xan\Documents\Projects\c_charp\PlatformusTest\PlatformusTest\Startup.cs:line 55
```

![image](https://user-images.githubusercontent.com/1754265/44247373-1d52af00-a20e-11e8-9e87-16bb88c2b51d.png)

It's looks like was missed Platformus.Configuration.Data.EntityFramework.SqlServer beta4 version.
![image](https://user-images.githubusercontent.com/1754265/44254950-93ffa480-a22e-11e8-8072-3d3d0e5b9baf.png)

**Comment by NickRimmer** [comment]
It's all with clear ASP.NET Core project, just added nugets as you describied in docs.

**Comment by DmitrySikorsky** [comment]
You can take https://github.com/Platformus/Platformus-Sample-Personal-Website, change all the 'SQLite' to 'SqlServer' and everything will work (if you change the connection string as well). Please remove bin and obj folders and then rebuild your solution to be sure that all the correct assemblies left in the project.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to open it any moment if you have additional questions.

**Comment by khalilme** [comment]
Exception Keyword not supported: 'initial catalog':
it's still the same, when I put a sql server connection

**Comment by DmitrySikorsky** [comment]
That is because your connection string is wrong. Initial catalog works for SQLite.

**Comment by khalilme** [comment]
no I'm right, the connection string is generated from VS, I didnt wrote it myself, also it's a valid connection, see below
https://www.connectionstrings.com/sql-server/
also I'm asp.net developer from 14 years, I know the connectionstring well

**Comment by DmitrySikorsky** [comment]
I don't know, that exception goes from the entity framework, not from Platformus. Platformus doesn't process the connection strings anyhow. So it is either wrong connection string, or you have specified wrong implementation of the data provider.

**Comment by vector-man** [comment]
@DmitrySikorsky Just wanted to let you know that I'm getting the error too. Installed all required packages from nuget and swapped all of the SQLite packages for PostgreSQL. Connection string appears correct and running a migration with a DBContext works fine, but it throws the same error at runtime that @NickRimmer received.

System.InvalidOperationException: 'Cannot resolve scoped service 'ExtCore.Data.Abstractions.IStorage' from root provider.'

Is it possibly related to this issue?: https://github.com/aspnet/DependencyInjection/issues/578 

Edit: Looks like the above link was the problem. Might want to add the workaround of using the first solution @NickRimmer used.
