### ISSUE TITLE
Error while uploading .webp image 

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#242]
Steps to reproduce:
1) Create a page class with an image field.
2) Start creating page object of that class, press [Upload...] button to select file for the image field.
3) Select any .webp image on your conpuuter. Its contents will be suuccessfully dispalyed in the dialog window.
4) Press [Done]. The =Image uploader= window will never close, and in the debugger console will appear such or similar error message:

_fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Parameter "source" must be not null. (Parameter 'source')
         at SixLabors.ThrowHelper.ThrowArgumentNullException(String name, String message)
         at SixLabors.ThrowHelper.ThrowArgumentNullExceptionForNotNull(String name)
         at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate(Image source, Configuration configuration, Action`1 operation)
         at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate(Image source, Action`1 operation)
         at Platformus.Images.Controllers.ImagesController.ProcessImage(Image image, Rectangle source, Size destination) in D:\Coding\Platformus\src\Platformus.Images\Controllers\ImageController.cs:line 80_

**Comment by rexTexTau** [comment]
New version of Sixlabors.ImageSharp supports webp image - so, I guess, lib update should fix this issue

**Comment by DmitrySikorsky** [comment]
Thanks, lib will be updated to 2.1.1 in version 3.0.0 release.
